### ISSUE TITLE
JS-T: HF20: Determine which tutorials are broken

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#129]
**AC**
- [x] In `# Results` list which tutorials are not working. Otherwise, report that all are working.

**Comment by roboza** [comment]
# Results

Configuration file needs to be updated with new demo account info.
Tutorials are unable to run on the testnet at this stage so testing was done on production.
Details of the compiling error has been added at the end of the list.
Testing on funds transfers could not be done as no test account is available on production for this purpose.


01 blog feed – cannot compile
02 steemconnect – cannot compile
03 client signing – ERROR: Unable to get head block. Tutorial may not function properly 
04 get posts – 	working
05 get post details - working
06 get voters list on post - working
07 get post comments - working
08 get account replies - working
09 get account comments - working
10 submit post – working
11 submit comment reply - working
12 edit content patching – working
13 stream blockchain transactions - working
14 reblogging post - working
15 search accounts - working
16 search tags – cannot compile
17 vote on content – working
18 follow a user - working
19 get follower and following list - working
20 account reputation - working
21 transfer steem and sbd - cannot test on production, no account available
22 witness listing and voting – working
23 claim rewards – working
24 power up steem - cannot test on production, no account available
25 power down - cannot test on production, no account available
26 create account – working via steemconnect
27 delegate power -  cannot test on production, no account available
28 set withdraw route - working
29 get delegations by user - working
30 grant posting permission - working
31 grant active permission - working


compiling error details:
possible error with node?

```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (..\16_search_tags\node_module
s\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (..\16_search_tags\node_mo
dules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

**Comment by relativityboy** [comment]
LGTM
