### ISSUE TITLE
no matter what if its related to steem its pretty safe to assume that the code wont work after you try to run it..

### ISSUE THREAD

**Issue by joshh71390** [steemit/devportal-tutorials-js#146]
every single tutorial in these series are broken...

**Comment by relativityboy** [comment]
I think we can see why right here:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/599528/217285234-bb8b2712-e19e-482f-9836-0300c2d88b6c.png">

At a guess Steemit didn't have the resources to maintain the tutorials after the big 2018 layoff. Maybe tidy up this ticket, make it look less like whining and more like something people can patch, and share it with the devs on whatever channels they're using. Might get some action. You can tell them to ping me. I can help with them learning how to run this repo if they need it.

**Comment by syvb** [comment]
The Hive (fork of Steem) docs have seen slightly more updates: https://developers.hive.io/tutorials-javascript/blog_feed.html ([source code](https://github.com/openhive-network/devportal/tree/master/_tutorials-javascript))
