### ISSUE TITLE
JS-T: Get comments by account

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#20]
Get comments of account

**AC**

- [x] Each account has its own posts and comments, example of using get_discussion_by_blog on profile (particularly comments section). Make mention of getState (and deprecation)
- [x] Format returned object in UI
- [x] Explain structure of returned object

**Comment by inertia186** [comment]
Watch out for `reblog` comments.  We should document that these come up in active blogs and might surprise new developers.

**Comment by feruzm** [comment]
@inertia186 This is mostly comments made by account. Not posts, it was covered in very first tutorial.
