### ISSUE TITLE
JS-T: Claim rewards

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#32]
Claim rewards - this is a simple version that replicates what Steemit.com does

**AC**

- [x] Claim specific part of reward
- [x] Claim all unclaimed rewards
- [x] Explanation of difference if any and why it is made manual as oppose to automatic and simply UI to display pending rewards
- [x] Note additional possibilities.
- [x] Create an issue that describes another tutorial with all possible complications.

**Comment by roboza** [comment]
https://github.com/steemit/steem-js/issues/215

**Comment by relativityboy** [comment]
Related gist from @inertia https://gist.github.com/inertia186/db94986d168f7b35034b0d7ccba6f2b4
