### ISSUE TITLE
JS-T: Convert SBD to STEEM

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#36]
Convert SBD to STEEM

**AC**

- [x] Convert SBD to STEEM
- [x] Explanation of feature with reference links (hot signing steemconnect)
- [x] Heavy admonishment against using this, use the internal market instead (under current economics).
- [x] directory should be `/32....`

**Comment by relativityboy** [comment]
This is a pretty uncommon need.
