### ISSUE TITLE
Ruby: Get posts from different category

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal-tutorials-js#63]
Get a post list using the various available categories (trending, hot, active, etc.)

This is a ruby version of #16 

**AC**

- [ ] Fetch trending, hot, active and created posts
- [ ] Output post details
- [ ] Error Handling

**Comment by relativityboy** [comment]
@inertia186 - if the code is going to ilve in /devportal this issue belongs on that repo.

**Comment by inertia186** [comment]
It certainly does.  Must have mixed up repos, again.

**Comment by inertia186** [comment]
Moved to: https://github.com/steemit/devportal/issues/166
