### ISSUE TITLE
JS-T: META: Update all relevant tutorials that use comment operation

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#82]
As a dev, I want easy access to details about the comment operation if I'm in a tutorial that uses it.
*This story was originally part of steemit/devportal#174. See it for context and details.

**AC**
- [x] related tutorials that affect comment operations link to the comment broadcast op in the developer portal site.

**Comment by roboza** [comment]
PR https://github.com/steemit/devportal/pull/237
