### ISSUE TITLE
Testnet reset, tutorials update

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#93]
https://steemit.com/steem/@almost-digital/psa-testnet-reset

Some tutorials iirc uses predefined users from above testnet and after reset they most likely won't work. 

**AC**

- [x] fix by creating accounts (demo, demo1, demo2, etc.)
- [x] list the tutorials which uses testnet
- [x] update readme if necessary about testnet reset
- [x] come up with solution that does not require rebuilding accounts every time the testnet is reset
- [x] results go in a comment titled `# Results`

**Comment by relativityboy** [comment]
Possibility: Steempunks public testnet.

**Comment by relativityboy** [comment]
@feruzm - we likely need you on other work.

**Comment by feruzm** [comment]
## Results

Solution is to point devs or users to Testnet and ask them to create account there, below tutorials needs to be updated to more generic approach rather than have predefined user credentials within source code.

Tutorials that uses Community Testnet.

https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/03_client_signing
https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/10_submit_post
https://github.com/steemit/devportal-tutorials-js/tree/master/tutorials/11_submit_comment_reply
https://github.com/steemit/devportal-tutorials-js/tree/master/tutorials/12_edit_content_patching
https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/17_vote_on_content
https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/18_follow_another_user
https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/20_transfer_steem_and_sbd
https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/21_witness_listing_and_voting


Suggestion to add these text in above tutorial's Readme.

```
This tutorial uses community Testnet and accounts are temporary and 
might be reset/purged at any point in future. 
Please create temporary accounts to test tutorials, 
essence of tutorials should still hold and be functional.
```

**Comment by relativityboy** [comment]
It might be good to have the text @feruzm has at the bottom of `# Results` be put in the main readme inside the `/tutorials` directory for each repo then each tutorial would have some text saying 

```
This tutorial uses a testnet by default instead of the main Steem blockchain. Please see [this note](link to main file) for more information about what that means.
```
It would make updating the repositories much easier as we switch testnets (future project) and lighten the cognitive burden for users who've already read through the main text.
